version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
      - "4000:4000"
    volumes:
      - .:/server
      - /server/node_modules
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
    restart: always

volumes:
  pgdata:
